In [8]:
import random

# Anzahl der Durchgänge für die Monte-Carlo-Simulation
num_iterations = 10

# Zähler für die Anzahl der Besuche auf jeder Seite
visits = {1: 0, 2: 0, 3: 0, 4: 0}

# Startseite wählen
current_page = random.choice(list(visits.keys()))

# Übergangsfunktion basierend auf den gegebenen Links
def transition(current):
    if current == 1:
        return random.choice([2, 3, 4])
    elif current == 2:
        return random.choice([3, 4])
    elif current == 3:
        return 1
    elif current == 4:
        return random.choice([1, 3])

# Monte-Carlo-Simulation des Surfverhaltens
for _ in range(num_iterations):
    current_page = transition(current_page)
    visits[current_page] += 1

# Normalisierung der Besuche, um relative Häufigkeiten zu erhalten
total_visits = sum(visits.values())
visit_frequencies = {page: count / total_visits for page, count in visits.items()}

visit_frequencies


3
1
3
1
3
1
3
1
4
3


{1: 0.4, 2: 0.0, 3: 0.5, 4: 0.1}

In [24]:
import numpy as np

# Definieren der Übergangsmatrix
P = np.array([
    [0.0375, 0.3208, 0.3208, 0.3208],
    [0.0375, 0.0375, 0.4625, 0.4625],
    [0.8875, 0.0375, 0.0375, 0.0375],
    [0.4625, 0.0375, 0.4625, 0.0375],
])

# Lösen des Gleichungssystems pi*P = pi
# Formulieren als (P^T - I)x = 0
# wobei I die Einheitsmatrix ist und x der Vektor pi ist.
print("Übergangsmatrix : \n", P)

print("Transpornierte Matrix: \n", P.T)

print("Einheitsmatrix : \n", np.eye(4))

A = P.T - np.eye(4)

print("Transponierte Matrix - Einheitsmatrix: \n", A)
# Hinzufügen der Bedingung, dass die Summe von pi 1 ergibt
A[-1] = [1, 1, 1, 1]

print("Hinzufügen der Bedingung: 1 1 1 1: \n", A)
# Rechte Seite des Gleichungssystems (alles 0 außer der letzten 1)
b = np.array([0, 0, 0, 1])

# Lösen des Gleichungssystems
pi = np.linalg.solve(A, b)
pi


Übergangsmatrix : 
 [[0.0375 0.3208 0.3208 0.3208]
 [0.0375 0.0375 0.4625 0.4625]
 [0.8875 0.0375 0.0375 0.0375]
 [0.4625 0.0375 0.4625 0.0375]]
Transpornierte Matrix: 
 [[0.0375 0.0375 0.8875 0.4625]
 [0.3208 0.0375 0.0375 0.0375]
 [0.3208 0.4625 0.0375 0.4625]
 [0.3208 0.4625 0.0375 0.0375]]
Einheitsmatrix : 
 [[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
Transponierte Matrix - Einheitsmatrix: 
 [[-0.9625  0.0375  0.8875  0.4625]
 [ 0.3208 -0.9625  0.0375  0.0375]
 [ 0.3208  0.4625 -0.9625  0.4625]
 [ 0.3208  0.4625  0.0375 -0.9625]]
Hinzufügen der Bedingung: 1 1 1 1: 
 [[-0.9625  0.0375  0.8875  0.4625]
 [ 0.3208 -0.9625  0.0375  0.0375]
 [ 0.3208  0.4625 -0.9625  0.4625]
 [ 1.      1.      1.      1.    ]]


array([0.36815166, 0.14179736, 0.28795292, 0.20209806])